### ISSUE TITLE
How to get the extension on the QLIK Cloud

### ISSUE THREAD

**Issue by oguchihy** [cleveranjos/br.com.clever.wordcloud#13]
After uploading the file from QLIK Sense Desktop, the SENSE Cloud does not present the wordcloud page.  I could not find a way to upload the extension into the cloud either.

**Comment by cleveranjos** [comment]
Qlik Sense Cloud does not support extensions

Em 2 de mar de 2017 03:44, "oguchihy" <notifications@github.com> escreveu:
