### ISSUE TITLE
Export to PDF does not work in Qlik Sense June 2017 Patch 2

### ISSUE THREAD

**Issue by mariansve** [cleveranjos/br.com.clever.wordcloud#14]
Hello,

export to PDF does not work in QS June 2017 Patch 2.
Can you please check and make following changes in the code - attached.

Thank you.
Marian
![capture](https://user-images.githubusercontent.com/31881928/30420366-9f88f4d6-9939-11e7-8e7e-3e6922194d13.PNG)

**Comment by cleveranjos** [comment]
Committed
